security:
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: Oob0FmH8l5IkiIuMaHmbxA2SrO/6o3yiRCtIs4JS7ZWBHirzUZwxCWbSLVbGT+f3H8cqUIcta5hkWfmo/+LJgA==, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        admin:
            pattern:    ^/admin
            http_basic: ~
            provider: in_memory

        main:
            pattern: /
            anonymous: ~
            knpu_guard:
                authenticators:
                    - app.api_token_authenticator
                # by default, use the start() function from FormLoginAuthenticator

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha512
